<?php
//
//	file: sys/utf8/charts/case.id_soft_dotted.php
//	author: Kevin Edwards - https://www.kncedwards.com/phpshape
//	begin: 07/08/2007
//	version: 0.0.2 - 29/01/2008
//	license: http://opensource.org/licenses/gpl-3.0.html GNU General Public License version 3 (GPLv3)
//
//	generated by gen_case_ident.php, utf-8 encoded
//

if ( !defined('SYS') )
{
	die('Not allowed');
}

$this->data['case.id_soft_dotted'] = array(
	'i' => 1, 'j' => 1, 'Ä¯' => 1, 'É‰' => 1, 'É¨' => 1, 'Ê' => 1, 'Ê²' => 1, 'Ï³' => 1, 'Ñ–' => 1, 'Ñ˜' => 1,
	'áµ¢' => 1, 'á¶–' => 1, 'á¶¤' => 1, 'á¶¨' => 1, 'á¸­' => 1, 'á»‹' => 1, 'â±' => 1, 'â…ˆ' => 1, 'â…‰' => 1, 'ð¢' => 1,
	'ð£' => 1, 'ð‘–' => 1, 'ð‘—' => 1, 'ð’Š' => 1, 'ð’‹' => 1, 'ð’¾' => 1, 'ð’¿' => 1, 'ð“²' => 1, 'ð“³' => 1, 'ð”¦' => 1,
	'ð”§' => 1, 'ð•š' => 1, 'ð•›' => 1, 'ð–Ž' => 1, 'ð–' => 1, 'ð—‚' => 1, 'ð—ƒ' => 1, 'ð—¶' => 1, 'ð—·' => 1, 'ð˜ª' => 1,
	'ð˜«' => 1, 'ð™ž' => 1, 'ð™Ÿ' => 1, 'ðš’' => 1, 'ðš“' => 1,
);

?>