<?php
//
//	file: sys/utf8/charts/case.lowers.s.php
//	author: Kevin Edwards - https://www.kncedwards.com/phpshape
//	begin: 06/08/2007
//	version: 0.0.2 - 29/01/2008
//	license: http://opensource.org/licenses/gpl-3.0.html GNU General Public License version 3 (GPLv3)
//
//	generated by gen_case_change.php, utf-8 encoded
//

if ( !defined('SYS') )
{
	die('Not allowed');
}

$this->data['case.lowers.s'] = array(
	'tr' => array(
		'*' => array('İ' => 'i'),
		'Not_Before_Dot' => array('I' => 'ı'),
	),
	'lt' => array(
		'*' => array('Ĩ' => 'i̇̃', 'Í' => 'i̇́', 'Ì' => 'i̇̀'),
		'More_Above' => array('Į' => 'į̇', 'J' => 'j̇', 'I' => 'i̇'),
	),
	'az' => array(
		'*' => array('İ' => 'i'),
		'Not_Before_Dot' => array('I' => 'ı'),
	),
	'*' => array(
		'*' => array(
			'ῼ' => 'ῳ', 'ῌ' => 'ῃ', 'ᾼ' => 'ᾳ', 'ᾯ' => 'ᾧ', 'ᾮ' => 'ᾦ', 'ᾭ' => 'ᾥ', 'ᾬ' => 'ᾤ', 'ᾫ' => 'ᾣ', 'ᾪ' => 'ᾢ', 'ᾩ' => 'ᾡ',
			'ᾨ' => 'ᾠ', 'ᾟ' => 'ᾗ', 'ᾞ' => 'ᾖ', 'ᾝ' => 'ᾕ', 'ᾜ' => 'ᾔ', 'ᾛ' => 'ᾓ', 'ᾚ' => 'ᾒ', 'ᾙ' => 'ᾑ', 'ᾘ' => 'ᾐ', 'ᾏ' => 'ᾇ',
			'ᾎ' => 'ᾆ', 'ᾍ' => 'ᾅ', 'ᾌ' => 'ᾄ', 'ᾋ' => 'ᾃ', 'ᾊ' => 'ᾂ', 'ᾉ' => 'ᾁ', 'ᾈ' => 'ᾀ', 'İ' => 'i̇',
		),
		'Final_Sigma' => array('Σ' => 'ς'),
	),
);

?>