<?php
//
//	file: sys/utf8/charts/case.fold_t.php
//	author: Kevin Edwards - https://www.kncedwards.com/phpshape
//	begin: 06/08/2007
//	version: 0.0.2 - 29/01/2008
//	license: http://opensource.org/licenses/gpl-3.0.html GNU General Public License version 3 (GPLv3)
//
//	generated by gen_case_folders.php, utf-8 encoded
//

if ( !defined('SYS') )
{
	die('Not allowed');
}

$this->data['case.fold_t'] = array(
	'İ' => 'i', 'I' => 'ı',
);

?>